name: ShowOffS
version: 2.0
main: me.crafter.mc.showoffs.ShowOffS
description: >
             Show your item to other players.
commands:
   showoff:
      permission: showoff.use
      usage: |
         /showoff
   showto:
      permission: showoff.use
      usage: |
         /showto <Player>
   i:
      permission: showoff.use
      usage: |
         /i